### ISSUE TITLE
Съезжают дни месяца

### ISSUE THREAD

**Issue by davidvirabian** [avatar-project/avatar-public-issues#2]
Съезжают дни месяца в календаре, на устройстве Xiaomi note 10
![2020-09-07 16 43 20](https://user-images.githubusercontent.com/70694105/92393898-44e47f00-f129-11ea-9d06-fa6a374aadcb.jpg)

**Comment by Papakkkarlo** [comment]
> Съезжают дни месяца в календаре, на устройстве Xiaomi note 10
Исправлено в 1.0.2
